version: '2'

services:
    web:
        image: lavoweb/php-7.4
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/app/
            - ./public:/var/www/html
        links:
            - db:db
    db:
        image: mysql:5.5
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        links:
            - db:db
    composer:
        image: composer:1.9
        command: ["composer", "install"]
        volumes:
            - ./:/app